export const API_ENDPOINT = process.env.EXPO_PUBLIC_API_END_POINT!;
export const PROJECT_ID = process.env.EXPO_PUBLIC_PROJECT_ID!;

export const PROJECT_NAME = process.env.EXPO_PUBLIC_PROJECT_NAME!;

export const USER_COLLECTION_ID = process.env.EXPO_PUBLIC_USERS_COLLECTION_ID!;

export const CHAT_COLLECTION_ID =
  process.env.EXPO_PUBLIC_CHAT_ROOM_COLLECTION_ID!;

export const CHAT_MESSAGES_COLLECTION_ID =
  process.env.EXPO_PUBLIC_MESSAGES_COLLECTION_ID!;

export const DATABASE_ID = process.env.EXPO_PUBLIC_DATABASE_ID!;
